### ISSUE TITLE
Cannot update via webUI from 9.0.9. RC1 to 9.1.5 RC1

### ISSUE THREAD

**Issue by davitol** [owncloud/administration#121]
@VicDeo 

> In a row
>  8.1.12 -> 8.2.11 RC1-> 9.0.9. RC1 ❌ 9.1.5 RC1

![screen shot 2017-04-05 at 18 09 22](https://cloud.githubusercontent.com/assets/10596560/24715292/2e94bfae-1a2b-11e7-99ae-d853922bba45.png)

**Comment by davitol** [comment]
@VicDeo The problem is related to 9.0.9. RC1 -> 9.1.5 RC1

**Comment by davitol** [comment]
@VicDeo JFYI It went fine via CLI

**Comment by PVince81** [comment]
@davitol log would have been nice or was there nothing in it ?

**Comment by davitol** [comment]
@PVince81 I think the log did not show info related to this error. OOTH I have already shared my test server credentials with @VicDeo where I was able to reproduce this issue

**Comment by davitol** [comment]
Recheck and no logs appear in owncloud.log file.

**Comment by VicDeo** [comment]
Fixes are merged, closing
