### ISSUE TITLE
Update server: Don't push outdated 10.0.0RC1 via beta channel

### ISSUE THREAD

**Issue by kdslkdsaldsal** [owncloud/administration#125]
As seen in https://github.com/owncloud/core/issues/27805 people could accidentally use the beta channel to update to the outdated 10.0.0 RC1 instead of the final 10.0.0 release.

cc @PVince81 @VicDeo

**Comment by kdslkdsaldsal** [comment]
Btw. it happened again the same way it happened between 9.0 and 9.1:

The impatient people trying to get to the next major release clicking on the "beta" channel providing oC 10.0 and accidentally upgrading their installation to a way outdated release.

IMHO a correct handling of updates/upgrades via the updater app needs to be added to the release checklist / procedure to avoid that stuff like this is happening.

**Comment by PVince81** [comment]
added to internal release checklist to also update beta to point to the latest stable if there is no update.

@VicDeo please take care

**Comment by VicDeo** [comment]
https://github.com/owncloud/administration/commit/4f2843b6350fe6cfd86b0aa151a91e4e2426e4e7

**Comment by VicDeo** [comment]
Beta channel is intended for testing. Any accidental usage is prodescuted :)
