### ISSUE TITLE
100-owncloud-inotify.conf should be renamed

### ISSUE THREAD

**Issue by ogoffart** [owncloud/administration#156]
As explained in https://github.com/owncloud/client/issues/2297#issuecomment-417931374

100-owncloud-inotify.conf does not have the desired effect as it is run before some other script that resets the limit to lower value.
Since the file are sorted in lexicographic order, renaming it to 99-... should work

**Comment by dschmidt** [comment]
Fixed in https://gitea.int.owncloud.com/ownbrander/scripting/commit/ee156340b886fc5f0b4e3fac71be142bf592bca8

**Comment by guruz** [comment]
Fixed in templates.
