### ISSUE TITLE
Migrate old translation-sync-apps Jenkins job

### ISSUE THREAD

**Issue by tboerger** [owncloud/administration#161]
Since the old Jenkins instance is dead we need to migrate the translation sync to Drone or our internal Jenkins instance.

All relevant Job descriptions are stored on Maggie, if you want to work on this task just contact @tboerger to get access to the files.

I suggest creating make targets within the related repositories that work similar to https://github.com/owncloud/user_management/pull/68/files.

**Comment by dschmidt** [comment]
The job operates on owncloud/apps.git which is archived and not used anymore afaict, thus I consider this job obsolete and won't port it to drone.
