### ISSUE TITLE
Repository for mingw on the build-clients/makewinlin.sh script is empty

### ISSUE THREAD

**Issue by tonnydourado** [owncloud/administration#17]
The repository at http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1 doesn't have any packages in it. Seems like they've been moved to http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2 (at least I could successfully build it using this repository. Currently the [script](https://github.com/owncloud/administration/blob/master/build-clients/makewinlin.sh) just doesn't find the packages and fail.

**Comment by lmartinez073** [comment]
Hi 

I am using the script and I am getting this error, your help will be appreciate.

CMake Error at cmake/modules/QtVersionAbstraction.cmake:21 (find_package):
  By not providing "FindQt5WebKitWidgets.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt5WebKitWidgets", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5WebKitWidgets"
  with any of the following names:

    Qt5WebKitWidgetsConfig.cmake
    qt5webkitwidgets-config.cmake

  Add the installation prefix of "Qt5WebKitWidgets" to CMAKE_PREFIX_PATH or
  set "Qt5WebKitWidgets_DIR" to a directory containing one of the above
  files.  If "Qt5WebKitWidgets" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:36 (include)


-- Configuring incomplete, errors occurred!
See also "/home/net9/owncloudclient/buildenv/windows/mirall-build/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'package'.  Stop.

Package(s) compiled. Installation file(s) can be found in "/home/net9/owncloudclient/client/".

**Comment by tonnydourado** [comment]
@lmartinez073 This is a closed issue, so maybe you should open another one. But, in the meantime, I had this same issue and IIRC, installing `mingw32-libqt5-qtwebkit-devel` solved it. Other stuff went wrong, though, with the v1.7.1 and v1.7.1-qt54 releases of the client.

**Comment by lmartinez073** [comment]
| thanks.
sorry to bother you. do you recommend me to follow up this procedure or is there another way?

Sent from Yahoo Mail on Android 
|  From:"Antonio Dourado" <notifications@github.com>
Date:Tue, Feb 17, 2015 at 10:47 AM
Subject:Re: [administration] Repository for mingw on the build-clients/makewinlin.sh script is empty (#17)



 @lmartinez073 This is a closed issue, so maybe you should open another one. But, in the meantime, I had this same issue and IIRC, installing mingw32-libqt5-qtwebkit-devel solved it. Other stuff went wrong, though, with the v1.7.1 and v1.7.1-qt54 releases of the client.—
Reply to this email directly or view it on GitHub.    |

 |

**Comment by tonnydourado** [comment]
@lmartinez073 What procedure? Installing `mingw32-libqt5-qtwebkit-devel`? Yes, I think it is worth a try, but I make no guarantee that the build is gonna be successful. All I know is that installing this package makes this particular error message go away. I didn't investigate it further, yet.

**Comment by ktWaran** [comment]
Could any one help me to sort this cmake error?

CMake Error at cmake/modules/QtVersionAbstraction.cmake:74 (find_package):
  By not providing "FindQt5LinguistTools.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt5LinguistTools", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5LinguistTools"
  with any of the following names:

    Qt5LinguistToolsConfig.cmake
    qt5linguisttools-config.cmake

  Add the installation prefix of "Qt5LinguistTools" to CMAKE_PREFIX_PATH or
  set "Qt5LinguistTools_DIR" to a directory containing one of the above
  files.  If "Qt5LinguistTools" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:54 (include)


-- Configuring incomplete, errors occurred!
See also "/home/kuga/client-build/CMakeFiles/CMakeOutput.log".

Thanks
