### ISSUE TITLE
Admin Page is Blank after upgrade to OC8

### ISSUE THREAD

**Issue by 19kestier** [owncloud/administration#29]
I upgraded my server on Digital Ocean running Ubuntu 14.04 Server to ownCloud 8. Now when I select Admin from the user dropdown, it gives me a blank page.
![screenshot 2015-02-09 at 8 26 10 pm](https://cloud.githubusercontent.com/assets/4749568/6119694/2daeb42a-b09a-11e4-8c38-935439c86481.png)

**Comment by karlitschek** [comment]
Can you please open this bug in the core repository? Thanks. It would be great if you could use the issue template.  https://github.com/owncloud/core/blob/master/CONTRIBUTING.md
