### ISSUE TITLE
Errors in package NSIS

### ISSUE THREAD

**Issue by mendesdouglas** [owncloud/administration#38]
CPack Error: Problem running NSIS command: "/usr/bin/makensis" "/home/douglasm/administration/build-clients/buildenv/windows/mirall-build/_CPack_Packages/unused/NSIS/project.nsi"

Anyone know what happen with this?
And how I do for solve !

Thanks

**Comment by mendesdouglas** [comment]
@danimo 
@kwillems 

Please help me I need, solve it.

**Comment by danimo** [comment]
Sorry, the bug tracker is not a support forum.

**Comment by mendesdouglas** [comment]
But I can't help anywhere.

**Comment by danimo** [comment]
Try building from a tag instead of master. Master is not meant for production.
