### ISSUE TITLE
dsc files for isv:ownCloud:desktop/owncloud-client is wrong

### ISSUE THREAD

**Issue by jnweiger** [owncloud/administration#44]
https://build.opensuse.org/package/view_file/isv:ownCloud:desktop/owncloud-client/owncloud-client.dsc?expand=1

has this:
<pre>
Source: ownCloud-client
Binary: ownCloud-client
</pre>

Both should be lower case owncloud-client 
this prevents 'apt-get source owncloud-client' from working.  or apt-get build-dep as used in  https://github.com/owncloud/client/blob/coverity_scan/.travis.yml

@LukasReschke Workaround:
apt-get build-dep owncloud-client || apt-get build-dep ownCloud-client

**Comment by jnweiger** [comment]
Fixed the metadata in https://build.opensuse.org/package/view_file/isv:ownCloud:desktop/owncloud-client/owncloud-client.dsc?expand=1

The proper fix needs to go into the templates and genbranding, without destroying ownbrander.
I'll leave that to Klaas to figure out how.

**Comment by dragotin** [comment]
Fixed in 9f194aa993a2fce103fdc5f500944a6bb9eea0c9

@jnweiger please test.

**Comment by jnweiger** [comment]
ownbrander will test it soon enough.
