### ISSUE TITLE
Create a script reporting all details about the installation & the bug report to be submitted to the bugtracker

### ISSUE THREAD

**Issue by hitam4450** [owncloud/administration#47]
Hi to All,

everybody who reports a bug or a strange behavior to the bugtracker is kindly asked by the robot to submit detailed information about his current installation: which apps are installed, which version, etc. and perhaps a logfile.

How about a button in the admin panel, which invokes a script, providing all necessary & required details, nicely formatted ready to be submitted to the bugtracker, including bug report and perhaps log file ???

After invoking, it should offer options to be able to select the right app which the user will report an issue on or select ALL just for documentation of the installation  !!

That certainly will make bug reporting an easy issue and will help the developers at the same time to keep track and work on the issues much smoother!

I am looking for your input!

regards, hitam4450

**Comment by hitam4450** [comment]
perhaps this could be done as a standalone solution first to be able to use it asap and later after refining it, being incorporated into the administration app!
Regards, hitam4450

**Comment by hitam4450** [comment]
Any, first sample script available for testing???

regards, hitam4450

**Comment by hitam4450** [comment]
Hi,
or make it a menu item Bug reporting (including log files, etc ??) in Administration and for  - complete - system documentation as well! 

regards, hitam4450

**Comment by hitam4450** [comment]
Any progress available yet, on this idea ????

**Comment by hitam4450** [comment]
After 4 months any progress to reported on this issue / idea?

regards, hitam4450

**Comment by DeepDiver1975** [comment]
There is work in progress by @LukasReschke

**Comment by hitam4450** [comment]
Three Thumbs up!

**Comment by hitam4450** [comment]
Any testing code available ????   I would love to help.....

**Comment by hitam4450** [comment]
Now Any testing code available, finally???? I would love to help..... and provide feedback!

**Comment by hitam4450** [comment]
The Bay isn't  born yet....after more then 1 year of pregnancy!
