### ISSUE TITLE
Select the default app other than files

### ISSUE THREAD

**Issue by hitam4450** [owncloud/administration#50]
How about an Option the be able to select another default app besides the files app, e.g. calendar, contacts  or any other installed and activated app??

To minimize discussions and meet personal preferences the option should appear in the  - personal - section ! What do you think about it??

Since not *everybody* is its *own* administrator - like me a - one user - one admin !

Especially in larger and large organizations it might be a *userfriendly* option!

regards, hitam4450

**Comment by karlitschek** [comment]
exists https://github.com/owncloud/core/blob/master/config/config.sample.php#L177

**Comment by hitam4450** [comment]
Hi,

thank you for answer and kind references. I do know this config option already and in a ONE USER - ONE ADMIN environment i(like mine and many others) this is Ok. However, as i pointed out in my message, I was thinking about organizations with several, maybe hundreds or even thousands of users, who not necessarily have access to the config.php !

regards, hitam4450

**Comment by karlitschek** [comment]
ok. please open a new issue in the core repository
