### ISSUE TITLE
Problem with "FindQt5WebKitWidgets.cmake" in CMAKE_MODULE_PATH

### ISSUE THREAD

**Issue by PariParia** [owncloud/administration#80]
I am building owncloud client on windows 7 .
I successfully build qtkeychain and previous steps according to what said here: https://doc.owncloud.org/desktop/2.1/building.html
 but then I could not build the project by this command:
cmake -G "MinGW Makefiles" ../client

got this error:
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: C:/Qt/Qt5.6.0/Tools/mingw492_32/bin/gcc.exe
-- Check for working C compiler: C:/Qt/Qt5.6.0/Tools/mingw492_32/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Qt/Qt5.6.0/Tools/mingw492_32/bin/g++.exe
-- Check for working CXX compiler: C:/Qt/Qt5.6.0/Tools/mingw492_32/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build of crashreporter disabled.
129c17651a56828ca6bfac60a0c9b44734ef9648
-- GIT_SHA1 129c17651a56828ca6bfac60a0c9b44734ef9648
-- Found OpenSSL: C:/OpenSSL-Win64/lib/ssleay32.lib;C:/OpenSSL-Win64/lib/libeay32.lib (found suitable version "1.0.2h", minimum required is "1.0.0")
-- Could NOT find INOTIFY (missing:  INOTIFY_INCLUDE_DIR INOTIFY_LIBRARY_DIR)
-- Could NOT find Sphinx (missing:  SPHINX_EXECUTABLE)
-- Could NOT find PdfLatex (missing:  PDFLATEX_EXECUTABLE)
-- Using own sqlite3 from H:/owncloud/client/src/3rdparty/sqlite3
-- Could NOT find ZLIB (missing:  ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
-- Performing Test WITH_FPIC
-- Performing Test WITH_FPIC - Success
-- Performing Test WITH_STACK_PROTECTOR
-- Performing Test WITH_STACK_PROTECTOR - Failed
-- Using own sqlite3 from H:/owncloud/client/src/3rdparty/sqlite3
-- Looking for argp.h
-- Looking for argp.h - not found
-- Looking for nanosleep in rt
-- Looking for nanosleep in rt - not found
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - not found
-- Looking for dlopen in dl
-- Looking for dlopen in dl - not found
-- Looking for asprintf
-- Looking for asprintf - found
-- Looking for fnmatch
-- Looking for fnmatch - not found
-- Looking for timegm
-- Looking for timegm - not found
-- Looking for strerror_r
-- Looking for strerror_r - not found
-- Looking for utimes
-- Looking for utimes - not found
-- Looking for lstat
-- Looking for lstat - not found
-- Looking for __mingw_asprintf
-- Looking for __mingw_asprintf - found
-- Found Qt5 core, checking for further dependencies...
CMake Error at cmake/modules/QtVersionAbstraction.cmake:25 (find_package):
  By not providing "FindQt5WebKitWidgets.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt5WebKitWidgets", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5WebKitWidgets"
  with any of the following names:

```
Qt5WebKitWidgetsConfig.cmake
qt5webkitwidgets-config.cmake
```

  Add the installation prefix of "Qt5WebKitWidgets" to CMAKE_PREFIX_PATH or
  set "Qt5WebKitWidgets_DIR" to a directory containing one of the above
  files.  If "Qt5WebKitWidgets" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  src/CMakeLists.txt:8 (include)

-- Configuring incomplete, errors occurred!
See also "H:/owncloud/client-build/CMakeFiles/CMakeOutput.log".
See also "H:/owncloud/client-build/CMakeFiles/CMakeError.log".

**Comment by PariParia** [comment]
somebody help please!

**Comment by RealRancor** [comment]
@PariaParia This is the wrong place to ask for support. Please close here and ask your question at:

https://mailman.owncloud.org/mailman/listinfo/devel

where it is more likely that some one is noticing it.

**Comment by astrosys** [comment]
@PariParia 
Open administration/build-clients/buildenv/windows/mirall-build/CMakeCache.txt

Make sure this path is right ( Qt5WebKitWidgets_DIR:PATH ) : 
//The directory containing a CMake configuration file for Qt5WebKitWidgets
Qt5WebKitWidgets_DIR:PATH=/usr/lib64/cmake/Qt5WebKitWidgets

this is works for me for that error

**Comment by RealRancor** [comment]
@PariParia Please close...
