### ISSUE TITLE
%nil changes need to be reverted

### ISSUE THREAD

**Issue by jnweiger** [owncloud/administration#81]
Regarding
https://github.com/owncloud/administration/commit/9a1a7e8fed696cb45d23ece1e6b46a94f130bcdb
and
https://github.com/owncloud/administration/commit/1a1d58a7da397d63e4544a7837cd899bb2097a78

Tested with CentOS7, the syntax 0%{?prerelease} and 0%{?prerelease:1} appears to evaluate to true, for both cases 
%define prerelease %nil
and
%define prerelease git20160518

With the above commits, we have inconsistent use of three differnt forms in the specfile
-  0%{?!prerelease}
-  0%{?!prerelease:1}
- "%{prerelease}" == ""

The %{?prerelease} syntax is used to catch the case, where the macro is undefined. This never happens. It is either defined as %nil (which evaluates to the empty but defined string), or it is defined to say gitXXX, betaXXX, or rcXXX

Where is the %{XXX:1} syntax defined? I have no idea what it should do. Please document.
As tested  on CentOS7, it evaluates always true.

I suggest to revert to consistent use of the latter. Not yet done. Both v2_2_0 and v2_2_1 templates affected.
Please document here, what issue should have been fixed.

**Comment by danimo** [comment]
@jnweiger Please feel free to revert. This was cargo-culting.

**Comment by jnweiger** [comment]
I believe that 2.2.0 was built in a strange way. 
The debian packages have 2.2.0%nil as version number. This will not be fixed by reverting the specfile changes. Is there more to be fixed?

 @dragotin what was the build procedure for 2.2.0 ? genbranding somehow or manually?
