### ISSUE TITLE
src/CMakeFiles/owncloudsync.dir/build.make:1047: *** target pattern contains no '%'.  Stop.

### ISSUE THREAD

**Issue by ghost** [owncloud/administration#95]
I am building owncloud client on openSuse 13.2
All dependency already completed.

I run this command in console : 
sudo bash makewinlin.sh -win -le

But i still got this error : 
-- Found Qt5 core, checking for further dependencies...
-- Using Qt 5!
-- GIT_SHA1 17a4299f74f4db7fc82f4b90f1e501c81288697b
-- neon-config executable: /usr/i686-w64-mingw32/sys-root/mingw/bin/neon-config
-- libneon has been compiled with LFS support
-- Could NOT find INOTIFY (missing:  INOTIFY_INCLUDE_DIR) 
-- Could NOT find PdfLatex (missing:  PDFLATEX_EXECUTABLE) 
-- Using own sqlite3 from /home/daydream/Desktop/own-client/administration/build-clients/buildenv/mirall/src/3rdparty/sqlite3
-- neon-config executable: /usr/i686-w64-mingw32/sys-root/mingw/bin/neon-config
-- libneon has been compiled with LFS support
-- Configuring done
CMake Warning (dev) in src/CMakeLists.txt:
  Policy CMP0020 is not set: Automatically link Qt executables to qtmain
  target on Windows.  Run "cmake --help-policy CMP0020" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /home/daydream/Desktop/own-client/administration/build-clients/buildenv/windows/mirall-build
[  0%] Built target httpbf
[  3%] Built target cstdlib
[ 13%] Built target ocsync
[ 14%] Automatic moc for target owncloud
[ 14%] Built target owncloud_automoc
[ 15%] Automatic moc for target owncloudsync
[ 15%] Built target owncloudsync_automoc
src/CMakeFiles/owncloudsync.dir/build.make:1047: **\* target pattern contains no '%'.  Stop.
CMakeFiles/Makefile2:400: recipe for target 'src/CMakeFiles/owncloudsync.dir/all' failed
make[1]: **\* [src/CMakeFiles/owncloudsync.dir/all] Error 2
Makefile:137: recipe for target 'all' failed
make: **\* [all] Error 2

[  0%] Built target httpbf
[  3%] Built target cstdlib
[ 13%] Built target ocsync
[ 14%] Automatic moc for target owncloud
[ 14%] Built target owncloud_automoc
[ 15%] Automatic moc for target owncloudsync
[ 15%] Built target owncloudsync_automoc
src/CMakeFiles/owncloudsync.dir/build.make:1047: **\* target pattern contains no '%'.  Stop.
CMakeFiles/Makefile2:400: recipe for target 'src/CMakeFiles/owncloudsync.dir/all' failed
make[1]: **\* [src/CMakeFiles/owncloudsync.dir/all] Error 2
Makefile:137: recipe for target 'all' failed
make: **\* [all] Error 2

Package(s) compiled. Installation file(s) can be found in "/home/daydream/Desktop/own-client/administration/build-clients/client/".

Have I missed something or what ? 
Please help , Thank you so much.

**Comment by RealRancor** [comment]
@astrosys This is a completely wrong place to ask for support of that stuff. Please close here and see https://owncloud.org/support/ for the correct places where you can get help.
